#!/bin/sh
#
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.
#
set -e

# Setting executable permissions
chmod +x /opt/apacheds-${version}/bin/apacheds
chmod +x /opt/apacheds-${version}/bin/wrapper
chmod +x /etc/init.d/apacheds-${version}-default

# Creating the apacheds user (only if needed)
USER=`eval "id -u -n apacheds 2>/dev/null || :"`
if [ ! "Xapacheds" = "X$USER" ]
then
	/usr/sbin/groupadd --system apacheds >/dev/null 2>&1 || :
	/usr/sbin/useradd --system -g apacheds -d /opt/apacheds-${version} apacheds >/dev/null 2>&1 || :
fi

# Modifying owner
chown -R apacheds:apacheds /opt/apacheds-${version}
chown -R apacheds:apacheds /var/lib/apacheds-${version}
chown root:root /etc/init.d/apacheds-${version}-default


