#!/bin/sh
#
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.
#
#

# Setting the correct permission on the org.apache.directory.server.plist file
#
chmod 644 /Library/LaunchDaemons/org.apache.directory.server.plist

#
# Launching the Apache DS daemon
#
RUNNING=`launchctl list | grep "org.apache.directory.server" | tail -1`
# Testing if the Apache DS daemon is already running
if [ "X$RUNNING" = "X" ]
then
	# If it is not running, we load it
    launchctl load /Library/LaunchDaemons/org.apache.directory.server.plist
else
	# If it is running, we unload it before reloading it
    launchctl unload /Library/LaunchDaemons/org.apache.directory.server.plist
    launchctl load /Library/LaunchDaemons/org.apache.directory.server.plist
fi


